# Generated by Django 3.2.2 on 2021-06-04 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availDates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
