# Generated by Django 3.2.2 on 2021-06-04 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210604_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availDates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, null=True, size=None),
        ),
    ]
