# Generated by Django 3.2.2 on 2021-06-04 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availDates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, null=True, size=None),
        ),
    ]
