# Generated by Django 3.2 on 2021-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210526_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
    ]
